name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Lint markdown files
        uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd
        with:
          config: '.markdownlint.json'
          globs: '**/*.md'
